### PR TITLE
Add logo and banner

### PR DESCRIPTION
**Pull request by drlaw1558**
This PR adds basic banner header/footer images for use by the notebooks.

### CODE REVIEW

**Review by sosey — CHANGES_REQUESTED** [review]
These images appear different from what is in the standards guide (and referenced from jdat repo and the template repo): https://github.com/spacetelescope/style-guides/tree/master/guides/images  ... did these come from the stsci branding package? 

I would have expected the logo images to be in _static as well, lemme go ask the template maintainer if there was a reason they aren't, we should probably update in the template repo as well

I'll add to my list to review that standards repo and update there for everyone, looks like it's been a while. That wont keep this PR from being submitted, but we need to make sure the branding is standard.

**Comment by drlaw1558** [comment]
Huh, I never knew about style-guides, or more likely had forgotten it existed.  Looks like my stsci_logo.png should be functionally identical to stsci-logo.png in the style guide.  The different one would be banner1.png that's intended to go at the top of the notebook; there's no equivalent in the style guide.  I'd propose that we use this opportunity to update the style guide to include such a banner.  That's been the single-most-useful thing about the MRS notebook to tell me instantly that notebooks I come across in the wild are based on my MRS notebook originally.  People modify the title and the text, but never seem to touch the banner.

**Comment by sosey** [comment]
@camipacifici you were probably involved in the jdat template notebook, was there a particular reason a banner at the top of the notebook wasn't used?

**Comment by sosey** [comment]
@drlaw1558 the stsci_logo file is meant to be the new footer logo?  The stsci_logo2 file is used in the left navbar for the html  generated pages. If so, should we change the name to be explicit that it's the footer, for clarity?

**Comment by drlaw1558** [comment]
Right, my stsci_logo is the footer.  Happy to change the name to something more clear.

**Comment by drlaw1558** [comment]
Now renamed to the more obvious stsci_header.png and stsci_footer.png

**Review by sosey — APPROVED** [review]

**Comment by sosey** [comment]
Let's add the images, if anything needs to be updated later we can submit another PR

**Comment by camipacifici** [comment]
No particular reason for no banner sorry.

**Pull request merged**
